name = "STSlib"
uuid = "a48b2831-cff4-4711-af15-66f5efafcdc7"
authors = ["Sebastian Callh"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
