name = "STSlib"
uuid = "a48b2831-cff4-4711-af15-66f5efafcdc7"
authors = ["Sebastian Callh"]
version = "0.1.0"

[deps]
GaussianDistributions = "43dcc890-d446-5863-8d1a-14597580bb8d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.7"